CREATE TABLE client(
id BIGINT PRIMARY KEY,
name VARCHAR(200) NOT NULL CHECK(LENGTH(name)>=3 AND LENGTH(name)<=200)
);

CREATE TABLE planet(
id VARCHAR(10) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
name VARCHAR(500) NOT NULL CHECK(LENGTH(name)>=1 AND LENGTH(name)<=500)
);

CREATE TABLE ticket(
id BIGINT PRIMARY KEY,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
client_id BIGINT NOT NULL,
from_planet_id VARCHAR(10) NOT NULL,
to_planet_id VARCHAR(10) NOT NULL
);

CREATE SEQUENCE client_seq START 1;
CREATE SEQUENCE ticket_seq START 1;

ALTER TABLE client ALTER COLUMN id SET DEFAULT nextval('client_seq');
ALTER TABLE ticket ALTER COLUMN id SET DEFAULT nextval('ticket_seq');

ALTER TABLE ticket ADD CONSTRAINT client_tickets_fk FOREIGN KEY (client_id)
REFERENCES client(id) ON DELETE CASCADE;
ALTER TABLE ticket ADD CONSTRAINT from_planet_fk FOREIGN KEY (from_planet_id)
REFERENCES planet(id) ON DELETE CASCADE;
ALTER TABLE ticket ADD CONSTRAINT to_planet_fk FOREIGN KEY (to_planet_id)
REFERENCES planet(id) ON DELETE CASCADE;

